version: "3.8"

# --- RETI ISOLATE
networks:
  public_net:
  keycloak_db_net:
  webapp_db_net:
  vault_net:

# --- VOLUMI PERSISTENTI
volumes:
  postgres_data:
    external: true
    # WARN: qui devi inserire il nome che docker ha dato (in teoria dovrebbe essere lo stesso)
    # per vedere il nome lancia "docker volume ls | grep postgres_data"
    name: keycloak_postgres_data
  mariadb_data:

services:
  # 1. VAULT
  vault:
    image: hashicorp/vault:1.15
    container_name: vault_spacehub
    cap_add:
      - IPC_LOCK
    volumes:
      # mapping cartelle locali (sinistra) e cartelle nel container (destra)
      # WARN: sposta le cartelle di vault nel progetto
      #- /opt/vault-data -> DIR/TO/PROJECT/vault/data
      #- /opt/vault-tls -> DIR/TO/PROJECT/vault/certs
      - ./vault/config/config.hcl:/vault/config/config.hcl:ro
      - ./vault/certs:/vault/certs:ro
      - ./vault/data:/vault/file
      - ./vault/policies:/vault/policies:ro
      # WARN: qui devi mettere il tuo percorso assoluto - serve per log su vault-audit.log
      - ./vault:/home/giu/Documenti/Securing-SpaceHub/Progetto/vault/
    working_dir: "/home/giu/Documenti/Securing-SpaceHub/Progetto/vault/"
    ports:
      - "8200:8200"
    command: server
    networks:
      - vault_net
      - webapp_db_net

  # 2. KEYCLOAK DATABASE
  postgres:
    image: postgres:15
    container_name: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    networks:
      - keycloak_db_net

  # 3. KEYCLOAK
  keycloak:
    build:
      context: ./keycloak
    container_name: keycloak
    depends_on:
      - postgres
    command: >
      start
      --https-certificate-file=/certs/keycloak.crt
      --https-certificate-key-file=/certs/keycloak.key
    volumes:
      - ./keycloak/certs:/certs:ro
    environment:
      KC_HTTPS_PROTOCOLS: TLSv1.3
      KC_SPI_THEME_CACHE_THEMES: false
      KC_SPI_THEME_CACHE_TEMPLATES: false
      KC_SPI_THEME_STATIC_MAX_AGE: -1
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}         
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASS}  
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}        
    ports:
      - "8443:8443"
    networks:
      - public_net
      - keycloak_db_net

  # 4. WEBAPP DATABASE (MariaDB)
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_spacehub
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: spacehub
    volumes:
      - mariadb_data:/var/lib/mysql
      #- ./database:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - webapp_db_net

  # 5. BACKEND (Node.JS)
  backend:
    build:
      context: ./backend
    container_name: backend_spacehub
    user: "node"
    depends_on:
      - mariadb
      - vault
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - VAULT_ADDR=https://vault:8200 
      - NODE_EXTRA_CA_CERTS=/usr/src/app/vault.crt
    volumes:
      - ./vault/certs/vault.crt:/usr/src/app/vault.crt:ro
      - ./backend/certs:/usr/src/app/certs:ro
    networks:
      - public_net
      - webapp_db_net
      - vault_net

  # 6. FRONTEND (Nginx)
  nginx:
    build:
      context: ./frontend
    container_name: nginx_frontend
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - public_net